Veterinaria/Models/Cliente.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Email { get; set; }
        public int IdSexo { get; set; }
        public string Telefono { get; set; }
        public int IdTienda { get; set; }
        public int Cedula { get; set; }
        public string Foto { get; set; }
    
        public virtual Sexo Sexo { get; set; }
        public virtual Tienda Tienda { get; set; }
    }
}

Veterinaria/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//using Veterinaria.DAL;
using Veterinaria.Models;

namespace Veterinaria.Controllers
{
	public class ClienteController : Controller
	{
		
		private VeterinariaEntities db = new VeterinariaEntities();
		public ActionResult Index()
		{
			if (Session["IdUsuario"] != null)
			{
				int IdUsuario = Convert.ToInt32( Session["IdUsuario"]);
				List<MascotasRegistradas> lista = new List<MascotasRegistradas>();
				var l = from registrarTarea in db.RegistrarTarea
						join mascota in db.Mascota on registrarTarea.IdMascota equals mascota.IdMascota
						join tarea in db.Tarea on registrarTarea.IdTarea equals tarea.IdTarea
						where mascota.IdUsuario == IdUsuario
						group new { mascota, registrarTarea, tarea } by new { mascota.IdMascota } into grupo
						select new
						{
							CostoTotal = grupo.Sum(s => s.tarea.Valor),
							MascotaId = grupo.Key.IdMascota,
							FechaProximaTarea = grupo.Max(t => t.registrarTarea.FechaTarea)
						};

				foreach( var i in l)
				{
					MascotasRegistradas mascotasR = new MascotasRegistradas();
					Mascota mascota = db.Mascota.Where(m => m.IdMascota == i.MascotaId).FirstOrDefault();
					mascotasR.Apodo = mascota.Apodo;
					mascotasR.Nombre = mascota.Nombre;
					mascotasR.FechaProximaTarea = i.FechaProximaTarea;
					mascotasR.CostoTotal = i.CostoTotal;
					mascotasR.Raza = mascota.Raza;
					var tareaPendiete = from registrar in db.RegistrarTarea
										join mas in db.Mascota on registrar.IdMascota equals mas.IdMascota
										where DbFunctions.TruncateTime(registrar.FechaTarea) == DbFunctions.TruncateTime(DateTime.Now) && mas.IdUsuario == IdUsuario
										group mas by new { mas.IdMascota } into g
										select new { valor = g.Count() };

					var tareasCompletadas = from registrar in db.RegistrarTarea
										join mas in db.Mascota on registrar.IdMascota equals mas.IdMascota
										where DbFunctions.TruncateTime(registrar.FechaTarea) < DbFunctions.TruncateTime(DateTime.Now) && mas.IdUsuario == IdUsuario
											group mas by new { mas.IdMascota } into g
										select new { valor = g.Count() };

					var totalTareas = (from r in db.RegistrarTarea
									 where r.IdMascota == i.MascotaId select r).Count();

					try
					{
						mascotasR.NumTareasPendientesDia = tareaPendiete.FirstOrDefault().valor;
					}
					catch (Exception)
					{
						
					}
					try
					{
						mascotasR.PorcentajeTareasRealizadas = (100 * tareasCompletadas.FirstOrDefault().valor) / totalTareas;
					}
					catch (Exception)
					{
						
					}
					
					
					lista.Add(mascotasR);
				}
				return View(lista);

			}
			else return RedirectToAction("Login", "Usuario");

		
		}

		public ActionResult ListarClientes()
		{
			string codigoPerfil = Session["CodigoPerfil"].ToString();
			if (codigoPerfil == "Admon")
			{
				return View(db.Cliente.ToList());
			}
			return View();
		}

		public ActionResult Crear(int? cedula)
		{
			//if (Session["IdUsuario"] != null)
			//{
				int cedulaSesion = Convert.ToInt32(Session["NombreUsuario"]);
				if (cedulaSesion > 0)
				{
					Cliente cli = new Cliente();
					cli = db.Cliente.Where(c => c.Cedula == cedulaSesion).FirstOrDefault();
					if (cli != null)
					{
						ConfigurarViewBag(cli);
						return View(cli);
					}

				}

				ConfigurarViewBag(new Cliente());
			Cliente cliente = new Cliente();
			if (cedula > 0)
			{
				cliente.Cedula = cedula.Value;
			}
				return View(cliente);
			//}
			//else return RedirectToAction("Login", "Usuario");
		}

		[HttpPost]
	
		public ActionResult Crear(Cliente cliente)
		{
			//if (ModelState.IsValid)
			//{
			string codigoPerfil = Session["CodigoPerfil"].ToString();
				if (cliente.IdCliente == 0)
				{
					db.Cliente.Add(cliente);
				}
				else
				{
					db.Entry(cliente).State = EntityState.Modified;
				}

				db.SaveChanges();
			ConfigurarViewBag(cliente);
			//return RedirectToAction("Index");
			if (codigoPerfil == "Admon")
			{
				return RedirectToAction("ListarClientes");
			}
			else return View(cliente);
			//}

		
			//return View(cliente);
		}

		public ActionResult Editar(int id)
		{
			Cliente cli = new Cliente();
			cli = db.Cliente.Where(c => c.IdCliente == id).FirstOrDefault();
			if (cli != null)
			{
				ConfigurarViewBag(cli);
				return View(cli);
			}
			return View();
		}

		public void ConfigurarViewBag(Cliente cli)
		{
			if (cli.IdCliente > 0)
			{
				ViewBag.IdTienda = new SelectList(db.Tienda, "IdTienda", "Nombre", cli.IdTienda);
				ViewBag.IdSexo = new SelectList(db.Sexo, "IdSexo", "NombreSexo", cli.IdSexo);
				ViewBag.IdCiudad = new SelectList(db.Ciudad, "IdCiudad", "Nombre", db.Tienda.Where(t => t.IdTienda == cli.IdTienda).FirstOrDefault().IdCiudad);
			}
			else
			{
				ViewBag.IdSexo = new SelectList(db.Sexo, "IdSexo", "NombreSexo");
				ViewBag.IdCiudad = new SelectList(db.Ciudad, "IdCiudad", "Nombre");

				ViewBag.IdTienda = new SelectList(db.Tienda.Where(t => t.IdCiudad == db.Ciudad.FirstOrDefault().IdCiudad), "IdTienda", "Nombre");
			}

		}

		public JsonResult GetStoreByCity(int id)
		{
			List<Tienda> lista = new List<Tienda>();
			lista = db.Tienda.Where(t => t.IdCiudad == id).ToList();
			SelectList listaSelect = new SelectList(lista, "IdTienda", "Nombre");
			return Json(listaSelect);

		}
	}
}

Veterinaria/Views/Cliente/Crear.cshtml
@model Veterinaria.Models.Cliente

@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Cliente</h4>
		<hr />
		@Html.HiddenFor(model => model.IdCliente)
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.Label("Fecha Nacimiento", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control date-picker" } })				
				@Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.Label("Sexo", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("IdSexo", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.IdSexo, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.Label("Ciudad", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("IdCiudad", null, htmlAttributes: new { @class = "form-control" })
			</div>
		</div>


		<div class="form-group">
			@Html.Label("Tienda", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("IdTienda", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.IdTienda, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">			

			@Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
			</div>
		</div>


		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Guardar" class="btn btn-default" />
			</div>
		</div>
	</div>
}


<script type="text/javascript">
    $('#IdCiudad').change(function ()
    {
        $("#IdTienda").empty();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("GetStoreByCity")', // we are calling json method
            dataType: 'json',
            data: { id: $("#IdCiudad").val() },
            success: function (states) {

                $.each(states, function (i, state) {
                    debugger;
                    $("#IdTienda").append('<option value="' + state.Value + '">' +
                         state.Text + '</option>');

                });
            },
        error: function (ex) {
            alert('Failed to retrieve states.' + ex);
        }
    });
    return false;

    });
</script>

Veterinaria/Views/Cliente/Editar.cshtml
@model Veterinaria.Models.Cliente

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

@using (Html.BeginForm("Crear", "Cliente", FormMethod.Post))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Cliente</h4>
		<hr />
		@Html.HiddenFor(model => model.IdCliente)
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.Label("Fecha Nacimiento", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control date-picker" } })
				@Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.Label("Sexo", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("IdSexo", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.IdSexo, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.Label("Ciudad", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("IdCiudad", null, htmlAttributes: new { @class = "form-control" })
			</div>
		</div>


		<div class="form-group">
			@Html.Label("Tienda", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("IdTienda", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.IdTienda, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">

			@Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
			</div>
		</div>


		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Guardar" class="btn btn-default" />
			</div>
		</div>
	</div>

	<div>
		@Html.ActionLink("Regresar a la lista", "ListarClientes")
	</div>
}


<script type="text/javascript">
    $('#IdCiudad').change(function ()
    {
        $("#IdTienda").empty();
        $.ajax({
            type: 'POST',
            url: '@Url.Action("GetStoreByCity")', // we are calling json method
            dataType: 'json',
            data: { id: $("#IdCiudad").val() },
            success: function (states) {

                $.each(states, function (i, state) {
                    debugger;
                    $("#IdTienda").append('<option value="' + state.Value + '">' +
                         state.Text + '</option>');

                });
            },
        error: function (ex) {
            alert('Failed to retrieve states.' + ex);
        }
    });
    return false;

    });
</script>

Veterinaria/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model IEnumerable<Veterinaria.Models.MascotasRegistradas>

@{
	ViewBag.Title = "Mascotas registradas";
	WebGrid grid = new WebGrid(Model);
	  }

@grid.GetHtml()

Veterinaria/Views/Cliente/ListarClientes.cshtml
@model IEnumerable<Veterinaria.Models.Cliente>

@{
    ViewBag.Title = "ListarClientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Clientes</h2>

<p>
    @Html.ActionLink("Nuevo", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cedula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo.NombreSexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tienda.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaNacimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cedula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Foto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexo.NombreSexo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tienda.Nombre)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.IdCliente }) |
            @Html.ActionLink("Detalles", "Detalles", new { id=item.IdCliente }) |
            @Html.ActionLink("Eliminar", "Eliminar", new { id=item.IdCliente })
        </td>
    </tr>
}

</table>